name: Daily Stock Check

on:
  schedule:
    - cron: "0 21 * * *" # Runs daily at 9pm UTC or 10am NZT
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-stock:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 python-dotenv

      # Run the script
      - name: Run stock check script
        env:
          URL: ${{ secrets.URL }}
          STOCK_SELECTOR: ${{ secrets.STOCK_SELECTOR }}
          ITEM_NAME_SELECTOR: ${{ secrets.ITEM_NAME_SELECTOR }}
          SIZE_SELECTOR: ${{ secrets.SIZE_SELECTOR }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python check_stock.py
